image: Ubuntu2004

environment:
  matrix:
    - RUBY_VERSION: 25
    - RUBY_VERSION: 26
    - RUBY_VERSION: 27

init:
  - sh: sudo apt-get install -y libzstd-dev

test_script:
  - sh: scripts/ci_test.sh

build: off
