name: test

on:
  - push

jobs:
  ubuntu:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        run: sudo apt-get install -y libzstd-dev

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:  
          ruby-version: ${{ matrix.ruby }}

      - name: CI test
        run: sudo scripts/ci_test.sh

  macos:
    strategy:
      matrix:
        ruby:
          - 2.5
          - 2.6
          - 2.7

    runs-on: macos-10.15

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Ruby setup
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: CI test
        run: sudo scripts/ci_test.sh

  # windows:
  #   runs-on: windows-2019
  #
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #
  #     - name: Setup dependencies
  #       uses: msys2/setup-msys2@v2
  #       with:
  #         install: >-
  #           mingw-w64-x86_64-gcc
  #           make
  #
  #     - name: CI test
  #       run: scripts/ci_test.sh
