name: test

on:
  - push

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dependencies
        run: sudo apt-get install -y libzstd-dev

      - name: CI test
        run: scripts/ci_test.sh

  macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: CI test
        run: scripts/ci_test.sh

  # windows:
  #   runs-on: windows-latest
  #
  #   defaults:
  #     run:
  #       shell: msys2 {0}
  #
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #
  #     - name: Setup dependencies
  #       uses: msys2/setup-msys2@v2
  #       with:
  #         install: >-
  #           mingw-w64-x86_64-gcc
  #           make
  #
  #     - name: CI test
  #       run: scripts/ci_test.sh
